version: "3.8"

services:
  web:
    image: img-eva-2
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
